/// Flutter icons CustomIcons
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData mail_outline = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData award = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData globe = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData leaf = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData book = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData fire_station = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData religious_christian = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData pinterest_squared = const IconData(0xf0d3, fontFamily: _kFontFam);
  static const IconData gplus_squared = const IconData(0xf0d4, fontFamily: _kFontFam);
  static const IconData youtube_squared = const IconData(0xf166, fontFamily: _kFontFam);
  static const IconData youtube = const IconData(0xf167, fontFamily: _kFontFam);
  static const IconData youtube_play = const IconData(0xf16a, fontFamily: _kFontFam);
  static const IconData instagram = const IconData(0xf16d, fontFamily: _kFontFam);
  static const IconData flickr = const IconData(0xf16e, fontFamily: _kFontFam);
  static const IconData tumblr_squared = const IconData(0xf174, fontFamily: _kFontFam);
  static const IconData foursquare = const IconData(0xf180, fontFamily: _kFontFam);
  static const IconData vimeo_squared = const IconData(0xf194, fontFamily: _kFontFam);
  static const IconData spotify = const IconData(0xf1bc, fontFamily: _kFontFam);
  static const IconData chart_line = const IconData(0xf201, fontFamily: _kFontFam);
  static const IconData facebook_official = const IconData(0xf230, fontFamily: _kFontFam);
  static const IconData whatsapp = const IconData(0xf232, fontFamily: _kFontFam);
  static const IconData snapchat_square = const IconData(0xf2ad, fontFamily: _kFontFam);
  static const IconData twitter_squared = const IconData(0xf304, fontFamily: _kFontFam);
  static const IconData spread = const IconData(0xf527, fontFamily: _kFontFam);
}
